language: android
env:
  global:
    - ANDROID_API_LEVEL=22
    - ANDROID_BUILD_TOOLS_VERSION=22.0.1
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=8
    
android:
  components:
    - android-22
    - build-tools-22.0.1
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
